### ISSUE TITLE
Can't run `python GAR.py` .

### ISSUE THREAD

**Issue by hahanigehaha233** [ruiyan1995/Group-Activity-Recognition#2]
There is some confidence in your update code, Please push the runnable code version. Thanks.

**Comment by hahanigehaha233** [comment]
PS: the problem is didn't download VD dataset.

**Comment by ruiyan1995** [comment]
You need to download the dataset manually in step ZERO. And I will clean some error in the update code.

**Comment by hahanigehaha233** [comment]
Thanks

**Comment by hahanigehaha233** [comment]
How many feature_size during test CAD data_set in action_level.py I can set.

**Comment by ruiyan1995** [comment]
> How many feature_size during test CAD data_set in action_level.py I can set.

As same as VD! The details are as follow,

In experiments on Collective Activity Dataset, 10 time-steps and 3000 hidden nodes are used for the Single-Person LSTM and a softmax layer is deployed for the classification in the “One” Network.
The number of sub-group is set to Nд = 1, namely, we do not need to divide the group. In “One to Key” Network (OKN), Interaction Bi-LSTM has a five time-steps (there are five individuals in one sub-group) and 1000 nodes; and Aggregation LSTM has five time-steps and 1000 nodes. Since the number of individuals in this dataset is varying from 1 to 12. We select five effective persons for each frame and
regard them as an entire group. If the number of persons is less than five, we take a full-zero matrix as the tracklets of new person.
